### ISSUE TITLE
callback value after code success 

### ISSUE THREAD

**Issue by iparkdza** [datacamp/datacamp-light#31] opened 2017-02-02 03:53 UTC
We try to use the datacamplight in our site. After have success_msg we want to change to the next exercise by link to the next page so are there the callback value to us?

**Comment by filipsch** [comment] 2017-02-02 09:01
@iparkdza Hi! Currently, we do not support such a thing, but it's a very good suggestion. We'll see if we can fit in somewhere. Until then, you think that there a way for you to probe the DCL iframe and check when the success message pops up by inspecting the DOM?

**Comment by filipsch** [comment] 2017-02-02 09:02
Related to #2

**Comment by ozonesk** [comment] 2017-02-05 12:01
@filipsch Actually, we just think to do something like @iparkdza said but not sure about how to probe  the DCL iframe and check when the success message pops up by inspecting the DOM

We don't know how to do it. If there are the ways to do, I want to see it. Thank you :)

**Comment by iamarcel** [comment] 2018-05-30 15:08
That's a great idea! Since we've rewritten DataCamp Light ([currently in beta](https://github.com/datacamp/datacamp-light/tree/beta)), this sounds like a good suggestion to add in there. There's already a global function to manually trigger DCL's initialization so we might just add another function that allows you to insert some of your own as a callback.

This issue is a duplicate of #2 though, so I'll close this one!

**Closed by iamarcel** 2018-05-30 15:08 UTC
Labels: feature

**Comment by iamarcel** [comment] 2018-06-21 06:13
@iparkdza @ozonesk 

This feature is now available (on the all-new DCL v2)! You can add a callback when a student starts DataCamp Light, when they submit a solution and when feedback for the exercise is returned (which includes whether the solution was correct).

[Check out the details on the documentation page.](https://cdn.datacamp.com/dcl-react-prod/index.html#tutorial-customizing-integrating)
