### ISSUE TITLE
matplotlib example plot display is broken

### ISSUE THREAD

**Issue by machow** [datacamp/datacamp-light#39] opened 2017-04-27 15:15 UTC
First exercise on...

https://cdn.datacamp.com/dcl/standalone-example.html

outputs:

![image](https://cloud.githubusercontent.com/assets/2574498/25490429/cfab7bc4-2b3a-11e7-8592-92ed33e77aba.png)

**Comment by filipsch** [comment] 2017-04-27 15:50
Duplicate of #40, closing this one.

**Closed by filipsch** 2017-04-27 15:50 UTC
